export const tempData = {
  email: "mheavers@mozilla.com",
  reputation: "medium",
  suspicious: false,
  references: 0,
  details: {
    blacklisted: false,
    malicious_activity: false,
    malicious_activity_recent: false,
    credentials_leaked: false,
    credentials_leaked_recent: false,
    data_breach: false,
    first_seen: "never",
    last_seen: "never",
    domain_exists: true,
    domain_reputation: "high",
    new_domain: false,
    days_since_domain_creation: 10044,
    suspicious_tld: false,
    spam: false,
    free_provider: false,
    disposable: false,
    deliverable: true,
    accept_all: true,
    valid_mx: true,
    primary_mx: "aspmx.l.google.com",
    spoofable: true,
    spf_strict: true,
    dmarc_enforced: false,
    profiles: [],
  },
};
